### ISSUE TITLE
Featured image enclosure fails for certain posts

### ISSUE THREAD

**Issue by atdr** [kasparsd/feed-image-enclosure#3]
As can be seen [from the feed validator](https://validator.w3.org/feed/check.cgi?url=berkeleysquares.co.uk%2Ffeed%2Frssnewsletter), the featured image isn't being added to certain posts on our site—any ideas why?

**Comment by kasparsd** [comment]
@atdr It adds only the featured images by default.

**Comment by atdr** [comment]
@kasparsd—

I completely understand the plugin is only for featured images, but **every post on the site** has a featured image ([we use them as thumbnails in archive views](https://www.berkeleysquares.co.uk/2017/03/)) and yet some feed entries don't have a featured image enclosed.

**Comment by kasparsd** [comment]
Thanks for the confirmation @atdr! Can you please debug this line by line in the plugin and see which check fails for those posts?
